# Change these first
owner: hgryoo # Your GitHub organization or username, where this repository lives
repo: upptime-cubrid # The name of this repository

sites:
  - name: CUBRID Website ORG
    url: https://www.cubrid.org/
  - name: CUBRID Website COM
    url: https://www.cubrid.com/
  - name: CUBRID JIRA
    url: http://jira.cubrid.org/
  - name: CUBRID QA Home
    url: https://qahome.cubrid.org/
  - name: CUBRID DEV
    url: https://dev.cubrid.org/
  - name: CUBRID Manual
    url: https://www.cubrid.org/manual/en/11.4/ # TODO: use latest instead

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: demo.upptime.js.org
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: CUBRID
  introTitle: "**CUBRID** is an open source DBMS optimized for OLTP. It offers great read and write performance than other database systems."
  introMessage: CUBRID status
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
